// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb4nk68OUcQaSiL89JYSIjs6g5Cs5bUU4',
    appId: '1:700016587374:android:f052c230082ec2964c2c7f',
    messagingSenderId: '700016587374',
    projectId: 'doctor-hunt-a86af',
    storageBucket: 'doctor-hunt-a86af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdKUhdjzxWAhoEGjohPrRUNbwoKjoFrkc',
    appId: '1:700016587374:ios:9956f4db5588eb464c2c7f',
    messagingSenderId: '700016587374',
    projectId: 'doctor-hunt-a86af',
    storageBucket: 'doctor-hunt-a86af.firebasestorage.app',
    iosBundleId: 'com.example.doctorHunt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdKUhdjzxWAhoEGjohPrRUNbwoKjoFrkc',
    appId: '1:700016587374:ios:9956f4db5588eb464c2c7f',
    messagingSenderId: '700016587374',
    projectId: 'doctor-hunt-a86af',
    storageBucket: 'doctor-hunt-a86af.firebasestorage.app',
    iosBundleId: 'com.example.doctorHunt',
  );

}